### ISSUE TITLE
python 2.6 bug

### ISSUE THREAD

**Issue by aureooms** [aureooms/sake#64]
File "lib/cpplint.py", line 4351, in cpplint.py

Failed example:

from lib.cpplint import _DropCommonSuffixes

Exception raised:

Traceback (most recent call last):

File "/opt/python/2.6.9/lib/python2.6/doctest.py", line 1253, in __run

compileflags, 1) in test.globs

File "<doctest cpplint.py[0]>", line 1, in <module>

from lib.cpplint import _DropCommonSuffixes

File "/home/travis/build/aureooms/sake/lib/__init__.py", line 28, in <module>

__init__()

File "/home/travis/build/aureooms/sake/lib/__init__.py", line 23, in __init__

__import__(module + '.' + name)

File "/home/travis/build/aureooms/sake/lib/cpm.py", line 6, in <module>

import lib.json, os.path, lib.fn, lib.github, lib.bitbucket, sake.github, sake.bitbucket

File "/home/travis/build/aureooms/sake/sake/__init__.py", line 6, in <module>

lib.pacman.__init__(sys.modules[__name__], os.path.dirname(os.path.abspath(__file__)))

File "/home/travis/build/aureooms/sake/lib/pacman.py", line 159, in __init__

s = importmodule(module + '.' + name)

File "/home/travis/build/aureooms/sake/sake/sty.py", line 6, in <module>

build = sake.text.concat

AttributeError: 'module' object has no attribute 'concat'

**Comment by aureooms** [comment]
#75
